FROM node:24-alpine AS builder

ARG SNAPSHOT="local"
ARG BUILD_DATE=""
ENV BUILD_HASH=$SNAPSHOT
ENV BUILD_DATE=$BUILD_DATE

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:24-alpine

ARG SNAPSHOT="local"
ARG BUILD_DATE=""

WORKDIR /app

EXPOSE 3000

ENV NODE_ENV=production
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000
ENV BUILD_HASH=$SNAPSHOT
ENV BUILD_DATE=$BUILD_DATE

COPY --from=builder /app/.output ./.output

CMD ["node", ".output/server/index.mjs"]
