on: push
name: Build and push container
jobs:
  dockerRegistry:
    name: Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push frontend
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        SNAPSHOT_TAG: $SNAPSHOT_TAG
      with:
        name: clelange/tdr-diff-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: SNAPSHOT_TAG
        workdir: ./
        snapshot: true
