on: push
name: Build and push container
jobs:
  dockerRegistry:
    name: Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Define variables
      id: var-def
      run: |
          TIMESTAMP=`date +%Y%m%d%H%M%S`
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-6)
          SNAPSHOT_TAG="${TIMESTAMP}${SHORT_SHA}"
          echo "${SNAPSHOT_TAG}"
          echo ::set-output name=snapshot-tag::"${SNAPSHOT_TAG}"
    - name: Test variables
      run: |
          echo ${{ steps.var-def.outputs.snapshot-tag }}
    - name: Build and push frontend
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        SNAPSHOT: ${{ steps.var-def.outputs.snapshot-tag }}
      with:
        name: clelange/tdr-diff-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: SNAPSHOT
        workdir: ./
        snapshot: true
