on: push
name: Build and push container to GHCR
jobs:
  dockerRegistry:
    name: Docker Registry (GHCR)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@master
    - name: Define variables
      id: var-def
      run: |
          TIMESTAMP=`date +%Y%m%d%H%M%S`
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-6)
          SNAPSHOT_TAG="${TIMESTAMP}${SHORT_SHA}"
          echo "${SNAPSHOT_TAG}"
          echo ::set-output name=snapshot-tag::"${SNAPSHOT_TAG}"
    - name: Test variables
      run: |
          echo ${{ steps.var-def.outputs.snapshot-tag }}
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: |
          ghcr.io/clelange/cms-tdr-diff-frontend:latest
          ghcr.io/clelange/cms-tdr-diff-frontend:${{ steps.var-def.outputs.snapshot-tag }}
        build-args: |
          SNAPSHOT=${{ steps.var-def.outputs.snapshot-tag }}
        file: cms-tdr-diff-frontend/Dockerfile.prod
